### PR TITLE
Added/changed a few translations

### PR DESCRIPTION
**Pull request by Bjartensen**
Added and changed translations for ~10-15 sentences.

### CODE REVIEW

**Comment by ftyers** [comment]
@Bjartensen the translations are great! Thanks... One thing though, you appear to have editted an older version of the file, which means that some of the annotations I made have been removed (see e.g. line 17330 in the diff).

If you can merge them that would be great, otherwise I can do it.

**Comment by ftyers** [comment]
@Bjartensen I've decided to merge the translations manually as there were only a few, and I'm about to get on a plane for 3 hours where I'm planning to do some more annotation. Perhaps we can take this up again tomorrow ? I've sent you a gtalk invite, but we could also chat on `#_u-dep` on IRC.

**Comment by Bjartensen** [comment]
@ftyers Cool thanks!

I've accepted your hangouts invite, but I can get an IRC client as well.

Safe trip.

**Comment by ftyers** [comment]
@Bjartensen I've decided to merge the translations manually as there were only a few, and I'm about to get on a plane for 3 hours where I'm planning to do some more annotation. Perhaps we can take this up again tomorrow ? I've sent you a gtalk invite, but we could also chat on `#_u-dep` on IRC.

**Comment by ftyers** [comment]
I'm going to close this for now as I've manually merged.

**Pull request closed without merging**
